openapi: 3.0.0
info:
  title: Deadlinetaskbot API
  description: API для взаимодействия с Deadlinetaskbot
  version: "1.0.0"
paths:
  /start:
    get:
      summary: Приветствие
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string